### ISSUE TITLE
Blitz GUI Roadmap

### ISSUE THREAD

**Issue by merelinguist** [blitz-js/blitz#605]
Some of the next steps for the GUI:

### CLI
- [ ] Open the GUI with a CLI command (https://github.com/blitz-js/blitz/issues/620)

### Project creation
- [x] Don’t assume usage of yarn (https://github.com/blitz-js/blitz/issues/606)
- [ ] Don’t assume usage of TypeScript (https://github.com/blitz-js/blitz/issues/618)
- [ ] Allow projects to be imported (https://github.com/blitz-js/blitz/issues/619)

### Extra
- [ ] Add task manager to run blitz start and more.
- [ ] Add more “modules”, e.g. view Prisma schema, view dependencies.
- [ ] Add a cli command to open the gui
- [ ] Better error handling
- [ ] Plugin system
- [ ] Integration with Prisma Studio, or our own implementation
- [ ] Multiplayer mode

**Comment by ditorojuan** [comment]
Nice work with the Infra, really like how it is looking.
I think I can start with the `Import existing projects` task

PS: idk if this is overkill but as an idea for looking at the prisma schemes we can add a graph so it is easier for the user to watch it?(this might be present in prisma studio, have not used it before lmk if this is just too overkill 😅)

**Comment by merelinguist** [comment]
Thanks! Please go right ahead with the project importing. DM me if you need any help :). And yes haha I had the same thing in mind for Prisma. It’d be cool to get a bird’s eye view of your schema.

**Comment by flybayer** [comment]
Oh yes, I'd love to have a visual schema graph of relationships and fields!

**Comment by merelinguist** [comment]
@flybayer Working on it right now!

<img width="569" alt="Screenshot 2020-06-02 at 16 23 06" src="https://user-images.githubusercontent.com/24858006/83538227-7bd54400-a4ed-11ea-8aa6-87b235ec64a5.png">

**Comment by peaonunes** [comment]
I’m happy to collaborate with `adding a cli command to open the gui`.

**Comment by jletey** [comment]
@merelinguist Should we maybe allow the user to configure a project to be JS or TS? In other words changing [this line](https://github.com/blitz-js/blitz/blob/canary/packages/gui/app/mutations/createProject.ts#L22)? I'd be happy to work on this :)

**Comment by merelinguist** [comment]
@peaonunes Awesome, go right ahead! Please DM me if you need any help.

**Comment by merelinguist** [comment]
@jletey That’d be a great idea! The task is yours 🦾.

**Comment by flybayer** [comment]
@jletey full JS support doesn't work yet, but we definitely want this option for when it does :)
