### ISSUE TITLE
Server Bugs Tracking Issue

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#93]
As I'm working on coding up the new architecture, I'm discovering a bunch of issues with our server package. So I'm listing them here instead of creating a bunch of independant issues.

- [x] Recursive path issue `.blitz/caches/dev/.blitz/caches/dev`
- [x] Bunch of `UnhandledPromiseRejectionWarning` errors
- [x] Rarely detects file changes. When it does, it's quite slow to detect and recompile
- [x] Top level pages dir should be optional (currently fails w/o it)
- [x] Should use `routes` dir instead of `pages` dir
- [x] `blitz build` and `blitz start -p` both fail
- [x] `app/pages` doesn't get copied to the built pages directory

**Comment by ryardley** [comment]
Have a look after the fixes I just did. Chokidar would have been stuck in an infinite loop because of the server path which would account for at least some of those issues. It's also important to build the server package or run root `yarn dev` in the background.

**Comment by ryardley** [comment]
Just checked off the things I think may be solved or possibly not quite clear.

**Comment by flybayer** [comment]
@ryardley sweet, much better now!

I just added a new one: `app/pages` doesn't get copied to the built pages directory. Nested ones get copied, but not the first level inside app.

**Comment by ryardley** [comment]
Yes that was by design. I think having a context was assumed but we can change that.

**Comment by flybayer** [comment]
Ok, yeah let's change that

**Comment by flybayer** [comment]
I added a new bug: `blitz build` and `blitz start -p` both fail

```
~/c/b/e/store> y blitz build
yarn run v1.19.1
$ /Users/b/c/blitz/node_modules/.bin/blitz build
Error: spawn /Users/b/c/blitz/examples/store/node_modules/.bin/next ENOENT
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Also, I changed the server to use routes instead of pages (in my new arch PR)

**Comment by ryardley** [comment]
Would it help to put these in separate issues? I can't reproduce the build an start issue.

**Comment by flybayer** [comment]
I opened #100 for the formik issue
